import {getChatGPTUser} from '../../chatgpt-auth';
import {readPet,writePet} from '../../../db/pets';
import {transition,type Action} from '../../engine';
import {z} from 'zod';
export const dynamic='force-dynamic';
const item=z.object({id:z.string().min(1).max(64),label:z.string().trim().min(1).max(90),kind:z.enum(['body','mind','heart'])}).strict();
const schema=z.object({revision:z.number().int().min(0),action:z.discriminatedUnion('type',[
 z.object({type:z.literal('adopt'),egg:z.number().int().min(0).max(5),name:z.string().trim().min(1).max(24),timezone:z.string().max(80),commitments:z.array(item).min(1).max(6)}).strict(),
 z.object({type:z.literal('feed'),food:z.enum(['meal','snack','treat'])}).strict(),z.object({type:z.literal('pet')}).strict(),z.object({type:z.literal('checkin'),done:z.array(z.string().max(64)).max(6)}).strict(),z.object({type:z.literal('commitments'),items:z.array(item).min(1).max(6)}).strict(),z.object({type:z.literal('evolve')}).strict(),z.object({type:z.literal('emerge')}).strict(),z.object({type:z.literal('nap')}).strict(),z.object({type:z.literal('wake')}).strict(),z.object({type:z.literal('readStory')}).strict()
])}).strict();
function json(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store'}});}
export async function GET(){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to save your companion.'},401);return json({...await readPet(user.userId),now:new Date().toISOString()});}catch(error){console.error('Unable to load companion',error);return json({error:'Your companion could not be loaded. Please try again.'},503);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Please use the app to care for your companion.'},403);const user=await getChatGPTUser();if(!user)return json({error:'Sign in to save your companion.'},401);const raw=await request.text();if(raw.length>12000)return json({error:'This update is too large.'},413);let parsed;try{parsed=schema.parse(JSON.parse(raw));}catch{return json({error:'Please check the details and try again.'},400);}const current=await readPet(user.userId);if(current.revision!==parsed.revision)return json({...current,error:'Your companion changed in another tab. Review and try again.',now:new Date().toISOString()},409);let pet;const now=new Date();try{pet=transition(current.pet,parsed.action as Action,now);}catch(error){return json({error:error instanceof Error?error.message:'Please try that again.'},400);}if(!await writePet(user.userId,pet,current.revision))return json({...await readPet(user.userId),error:'Another update arrived first. Review and try again.',now:now.toISOString()},409);return json({pet,revision:current.revision+1,now:now.toISOString()});}catch(error){console.error('Unable to save companion',error);return json({error:'Your update was not saved. Please try again.'},503);}}
